AllCops:
  Exclude:
  - 'app/channels/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'bin/*'
  - 'lib/tasks/**/*'
  - 'spec/factories/**/*'
  - 'spec/factories/**/*'
  - 'spec/requests/tickets_spec.rb'

require:
- rubocop-rspec

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'app/admin/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

Lint/Debugger:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false